config/routes.rb
Rails.application.routes.draw do
  resources :aplicacions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aplicacion.rb
class Aplicacion < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/aplicacions_controller.rb
class AplicacionsController < ApplicationController
  before_action :set_aplicacion, only: %i[ show edit update destroy ]

  # GET /aplicacions or /aplicacions.json
  def index
    @aplicacions = Aplicacion.all
  end

  # GET /aplicacions/1 or /aplicacions/1.json
  def show
  end

  # GET /aplicacions/new
  def new
    @aplicacion = Aplicacion.new
  end

  # GET /aplicacions/1/edit
  def edit
  end

  # POST /aplicacions or /aplicacions.json
  def create
    @aplicacion = Aplicacion.new(aplicacion_params)

    respond_to do |format|
      if @aplicacion.save
        format.html { redirect_to aplicacion_url(@aplicacion), notice: "Aplicacion was successfully created." }
        format.json { render :show, status: :created, location: @aplicacion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aplicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aplicacions/1 or /aplicacions/1.json
  def update
    respond_to do |format|
      if @aplicacion.update(aplicacion_params)
        format.html { redirect_to aplicacion_url(@aplicacion), notice: "Aplicacion was successfully updated." }
        format.json { render :show, status: :ok, location: @aplicacion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aplicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aplicacions/1 or /aplicacions/1.json
  def destroy
    @aplicacion.destroy

    respond_to do |format|
      format.html { redirect_to aplicacions_url, notice: "Aplicacion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aplicacion
      @aplicacion = Aplicacion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aplicacion_params
      params.require(:aplicacion).permit(:nombre, :descripcion)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/aplicacions_helper.rb
module AplicacionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aplicacions/_form.html.erb
<%= form_with(model: aplicacion) do |form| %>
  <% if aplicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aplicacion.errors.count, "error") %> prohibited this aplicacion from being saved:</h2>

      <ul>
        <% aplicacion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aplicacions/edit.html.erb
<h1>Editing Aplicacion</h1>

<%= render 'form', aplicacion: @aplicacion %>

<%= link_to 'Show', @aplicacion %> |
<%= link_to 'Back', aplicacions_path %>

app/views/aplicacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aplicacions</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aplicacions.each do |aplicacion| %>
      <tr>
        <td><%= aplicacion.nombre %></td>
        <td><%= aplicacion.descripcion %></td>
        <td><%= link_to 'Show', aplicacion %></td>
        <td><%= link_to 'Edit', edit_aplicacion_path(aplicacion) %></td>
        <td><%= link_to 'Destroy', aplicacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aplicacion', new_aplicacion_path %>

app/views/aplicacions/new.html.erb
<h1>New Aplicacion</h1>

<%= render 'form', aplicacion: @aplicacion %>

<%= link_to 'Back', aplicacions_path %>

app/views/aplicacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @aplicacion.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @aplicacion.descripcion %>
</p>

<%= link_to 'Edit', edit_aplicacion_path(@aplicacion) %> |
<%= link_to 'Back', aplicacions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PgRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>